ports:
  - port: 8080
    onOpen: open-browser
tasks:
  - init: >
      nvm install 14
  - command: >
      nvm install 14 &&
      cp .env.example .env &&
      npm i vercel -g &&
      npm install &&
      npm run start
